CompArchivos/CompArchivos/Models/FileInformation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CompArchivos.Models
{
    public class FileInformation
    {
        public int FileId { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public int MaxDescarga { get; set; }

        public Guid Guid { get; set; }
    }
}

CompArchivos/CompArchivos/Controllers/FileController.cs
using CompArchivos.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CompArchivos.Controllers
{
    public class FileController : Controller
    {

        DownloadFiles obj;
        public FileController()
        {
            obj = new DownloadFiles();
        }


        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file, string max_descarga)
        {
            try
            {
                Guid fileGuid = Guid.NewGuid();
                if (file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    dbArchivosManager.AddArchivo(fileName, fileGuid.ToString(), max_descarga);
                    var path = Path.Combine(Server.MapPath("~/archivos/"), fileGuid.ToString());
                    file.SaveAs(path);
                }
                //ViewBag.Message = "Archivo cargado, para compartir el archivo usa el siguiente link: " + HttpContext.Request.Url.Host + "/DownloadGuid?fileGuid=" + fileGuid.ToString();
                TempData["Message"] = "Archivo cargado, para compartir el archivo usa el siguiente link: " + HttpContext.Request.Url.Host + "/File/DownloadGuid?fileGuid=" + fileGuid.ToString();
                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.Message = "Carga fallida";
                return RedirectToAction("Upload");
            }
        }

        [HttpGet]
        public ActionResult UploadFile()
        {
            return View();
        }

        public ActionResult Index()
        {
            if (TempData["Message"] == null) TempData["Message"] = "Hola :)";
            var filesCollection = obj.GetFiles();
            return View(filesCollection);
        }

        public FileResult Download(string FileID)
        {
            int CurrentFileID = Convert.ToInt32(FileID);
            var filesCol = obj.GetFiles();
            string CurrentFileName = (from fls in filesCol
                                      where fls.FileId == CurrentFileID
                                      select fls.FilePath).First();

            string contentType = string.Empty;

            if (CurrentFileName.Contains(".pdf"))
            {
                contentType = "application/pdf";
            }
            else if (CurrentFileName.Contains(".docx"))
            {
                contentType = "application/docx";
            }
            else
            {
                contentType = "application/octet-stream";
            }

            return File(CurrentFileName, contentType, CurrentFileName);
        }


        [HttpGet]
        public ActionResult FileError()
        {
            return View("NoDisponible");
        }

        private void RemoveFile(string fileGuid)
        {
            FileInformation fileinf = dbArchivosManager.GetArchivoXguid(fileGuid.ToString());
            try
            {
                var fileName = Path.GetFileName(fileinf.FileName);
                var path = Path.Combine(Server.MapPath("~/archivos/"), fileGuid.ToString());

                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);
                    var result = dbArchivosManager.DeleteArchivo(fileGuid);
                }
            }
            catch (IOException)
            {

            }
        }

        public ActionResult DownloadGuid(string fileGuid)
        {
             
            FileInformation fileinf = dbArchivosManager.GetArchivoXguid(fileGuid.ToString());

            
            if (fileinf == null)
            {
                return RedirectToAction("FileError");
            }
            else if(fileinf.MaxDescarga <= 0)
            {
                return RedirectToAction("FileError");
            }

            else
            {
                var result = dbArchivosManager.Substract(fileGuid);
                string contentType = string.Empty;

                if (fileinf.FileName.Contains(".pdf"))
                {
                    contentType = "application/pdf";
                }
                else if (fileinf.FileName.Contains(".docx"))
                {
                    contentType = "application/docx";
                }
                else
                {
                    contentType = "application/octet-stream";
                }
                var path = Path.Combine(Server.MapPath("~/archivos/"), fileGuid.ToString());
                var bytes = System.IO.File.ReadAllBytes(path);
                if (fileinf.MaxDescarga == 1)
                    RemoveFile(fileGuid);
                return File(bytes, contentType, fileinf.FileName);
            }
        }

    }
}

CompArchivos/CompArchivos/Views/File/Index.cshtml
@model IEnumerable<CompArchivos.Models.FileInformation>

@{
    ViewBag.Title = "Index";
}

<h1>Menú</h1>

<h2>
    @Html.ActionLink("Compartir archivos", "UploadFile")
</h2>

<h3>
    @*<span>Mensaje del sistema: @ViewBag.Message</span>*@
    <span>Mensaje del sistema: @TempData["Message"] </span> 
</h3>
 

CompArchivos/CompArchivos/Views/File/NoDisponible.cshtml
@{
    ViewBag.Title = "Error";
}

<h2>Archivo no disponible</h2>

<p>El archivo especificado no esta disponible o ha superado el maximo de descargas.</p>

CompArchivos/CompArchivos/Views/File/UploadFile.cshtml
@{
    ViewBag.Title = "UploadFile";
}

<h2>UploadFile</h2>

@using (Html.BeginForm("Upload", "File", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <div>
        @Html.TextBox("file", "", new { type = "file" }) <br />

        <label>Cantidad maxima de descargas</label>
        <input type="number" value="1" name="max_descarga"/>

        <input type="submit" value="Upload" />

        @TempData["Message"]

    </div>


}  

CompArchivos/CompArchivos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DarkFileSharedExpress</title>
    @*<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />*@
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/styles/style.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("DarkFileSharedExpress", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - DarkFileSharedExpress</p>
            <p>Desarrollo: Marco_G, Cynthia_S,Alfredo_M,Johan_V,Olman_M,Jose_Ch,Roberto_Z,Randall_Li</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>